<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Users;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUserMaterialsOrderedByRef(Users $user)
    {
        return $this->getEntityManager()
            ->createQuery(
					'SELECT m
					   FROM AppBundle:Materials m
					  WHERE m.userid = :id
				   ORDER BY m.ref ASC'
				)->setParameter('id', $user->getId())
            ->getResult();
    }
}
