<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Models;
use AppBundle\Entity\Users;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUserModelsOrderedByUser(){
		return $this->getEntityManager()
            ->createQuery(
					'SELECT m
					   FROM AppBundle:Models m
				   ORDER BY m.userid ASC'
				)
            ->getResult();
	}
	
	public function findUserModelsOrderedByCategory(Users $user)
    {
        return $this->getEntityManager()
            ->createQuery(
					'SELECT m
					   FROM AppBundle:Models m
					  WHERE m.userid = :id
				   ORDER BY m.categoryid ASC'
				)->setParameter('id', $user->getId())
            ->getResult();
    }
	
	public function findUserModelsCategories(Users $user)
    {
        return $this->getEntityManager()
            ->createQuery(
					'SELECT m
					   FROM AppBundle:Models m
					  WHERE m.userid = :id
				   GROUP BY m.categoryid'
				)->setParameter('id', $user->getId())
            ->getResult();
    }
	
	public function findModelsByUser($user){
		return $this->getEntityManager()
            ->createQuery(
					'SELECT m
					   FROM AppBundle:Models m
					  WHERE m.userid = :id
				   ORDER BY m.categoryid, m.name ASC'
				)->setParameter('id', $user->getId())
            ->getResult();
	}
}