<?php

namespace AppBundle\Repository;

/**
 * ShowcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowcaseRepository extends \Doctrine\ORM\EntityRepository
{
	public function findUserShowcasesOrderedByUser(){
		return $this->getEntityManager()
            ->createQuery(
					'SELECT s
					   FROM AppBundle:Showcases s
				   ORDER BY s.userid, s.name ASC'
				)
            ->getResult();
	}
	
	public function findShowcasesByToken($token){
		return $this->getEntityManager()
            ->createQuery(
					'SELECT s
					   FROM AppBundle:Showcases s
					  WHERE s.token = :token'
				)->setParameter('token', $token)
            ->getResult();
	}
}